/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class starcom_gui_appindicator_NativeAppIndicator */

#ifndef _Included_starcom_gui_appindicator_NativeAppIndicator
#define _Included_starcom_gui_appindicator_NativeAppIndicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     starcom_gui_appindicator_NativeAppIndicator
 * Method:    init
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;[Ljava/lang/Object;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_starcom_gui_appindicator_NativeAppIndicator_init
  (JNIEnv *, jobject, jstring, jstring, jstring, jobjectArray, jstring);

/*
 * Class:     starcom_gui_appindicator_NativeAppIndicator
 * Method:    upIcons
 * Signature: (Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_starcom_gui_appindicator_NativeAppIndicator_upIcons
  (JNIEnv *, jobject, jstring, jstring);

/*
 * Class:     starcom_gui_appindicator_NativeAppIndicator
 * Method:    quitApp
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_starcom_gui_appindicator_NativeAppIndicator_quitApp
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
