/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class NativeAppIndicator */

#ifndef _Included_NativeAppIndicator
#define _Included_NativeAppIndicator
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     NativeAppIndicator
 * Method:    init
 * Signature: (Ljava/lang/String;[Ljava/lang/String;Ljava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_NativeAppIndicator_init
  (JNIEnv *, jobject, jstring, jobjectArray, jstring);

/*
 * Class:     NativeAppIndicator
 * Method:    quit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_NativeAppIndicator_quit
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
